### ISSUE TITLE
Document with example modifications to connect to node-opcua simple_server.js

### ISSUE THREAD

**Issue by gt-atx** [node-opcua/node-opcua-htmlpanel#1]
Would it be possible for you to post an example of what needs to be modified to connect to the simple_server example from node-opcua-htmlpanel?  I have installed node-opcua and initialized simple_server.js.  I am a novice, so I haven't been able to figure out what/where to modify node-opcua-htmlpanel to connect to the simple_server.  Can you please assist?  Thank you for your outstanding contributions.

**Comment by erossignon** [comment]
readme.md updated
