### ISSUE TITLE
not able to find simple_server.js 

### ISSUE THREAD

**Issue by ajitrishabh** [node-opcua/node-opcua-htmlpanel#10]
i did the installation 
but when i ran this command to start server
`node node_modules/node-opcua/bin/simple_server.js > /dev/null &`
i got `The system cannot find the path specified.`
there is no folder in `bin` in `node-opcua`
need help.

**Comment by simontaurus** [comment]
Tutorial is not up to date. Run 
`npm install node-opcua-samples --unsafe-perms`
first. Change 
`const endpointUrl = "opc.tcp://opcuademo.sterfive.com:26543/UA/SampleServer";`
to
`const endpointUrl = "opc.tcp://" + hostname + ":26543/UA/SampleServer";`
in the app.js in the demo code.
Then run 
`node node_modules/node-opcua-samples/bin/simple_server.js > /dev/null &`
and
`node app.js`
, open 
`http://localhost:3700/`
in a browser.

**Comment by erossignon** [comment]
Thank you for the tip.
