### ISSUE TITLE
data of the OPC UA client is not transferred to the html server

### ISSUE THREAD

**Issue by bnouhanna** [node-opcua/node-opcua-htmlpanel#2]
The node OPCUA client seems to connect to the OPC UA server on my rpi (used simple client and simple server files). I can access the html file index.html, but the sensor data can t be viewed only the graph with no display of data. 

PlZ help.

**Comment by erossignon** [comment]
Thank you, this should be fixed now in d513b371f3b4ba4e8699056f9a7cb8cbfec6bb78 
I have also improved the installation instruction in the readme.

Let me know if it is working better now.

**Comment by bnouhanna** [comment]
Thank you very much for ur reply. I ll try it and get back to u. Thx a lot

**Comment by bnouhanna** [comment]
Worked perfectly. Thx

**Comment by bnouhanna** [comment]
I have another question. So far I ve been able to read variables. How can I change value of a variable instead of read I would write. In this example to be able to change the value of a variable from the html panel?

**Comment by erossignon** [comment]
It's up to you, really, the node-opcua-htmlpanel is just provided as a sample application for demo only.
I will welcome any contributions that provides `write` capabilities. Please feel free to contribute.
A good starting point to understand how to use the node-opcua api is to scrutanize the unit tests.

for instance here for the session#write api:
https://github.com/node-opcua/node-opcua/blob/master/test/end_to_end/u_test_e2e_writeUseCase.js
