### ISSUE TITLE
http://localhost:3700 simply states "It works!", no panel

### ISSUE THREAD

**Issue by djrobby** [node-opcua/node-opcua-htmlpanel#5]
When I visit http://localhost:3700, it simply states "It works!" with no gauge or chart. Is this an issue? I followed the install instructions.

**Comment by djrobby** [comment]
Replacing `app.js` lines [77-80](https://github.com/node-opcua/node-opcua-htmlpanel/blob/master/app.js#L77) from:

```
    var app = express();
    app.get("/", function(req, res){
        res.send("It works!");
    });
```

to:

```
    var app = express();
    app.set('view engine', 'html');
    app.use(express.static(__dirname + '/'));
    app.set('views', __dirname + '/');
    app.get("/", function(req, res){
        res.render('index.html');
    });
```

Fixed this problem! @erossignon please update the repo accordingly. Thank you!

**Comment by pflugs30** [comment]
worked for me, too.  thanks, @djrobby !
